### ISSUE TITLE
troubleshoot mtar build

### ISSUE THREAD

**Issue by kaoskater08** [SAP/devops-docker-mta-archive-builder#24]
Hi all, 

I'm attempting to use this image and build one of our projects. I get the same error each run and hoping for a little guidance on how to troubleshoot. 

When I run the docker command it begins the build process then fails invoking grunt: 
```
$ docker run --rm -v "${PWD}":/project -it ppiper/mta-archive-builder:latest mtaBuild --mtar test.mtar --build-target NEO build
SAP Multitarget Application Archive Builder 1.1.19
Module "cos": invoking npm install
Module "cos": command output
audited 1266 packages in 15.041s
found 36 vulnerabilities (7 low, 7 moderate, 22 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Module "cos": invoking grunt
ERROR: Failed to build module "cos". Command execution failed
```

Is there a way to output more logs or a way to troubleshoot? I can successfully build this application in WebIDE.

**Comment by daniel-kurzynski** [comment]
Hi,

First of all please be aware that the SAP Multitarget Application Archive Builder is deprecated: https://help.sap.com/viewer/58746c584026430a890170ac4d87d03b/Cloud/en-US

The new tool is the Cloud MTA Build Tool: https://github.com/SAP/cloud-mta-build-tool
You can find the corresponding docker image here: https://hub.docker.com/r/devxci/mbtci

Regarding your issue: Have you also tried to build the project using the "SAP Multitarget Application Archive Builder" without docker? You can download from here: https://tools.hana.ondemand.com/#cloud

What happens if you run the grunt build of the module cos directly (without calling it form MTA)?

**Comment by fwilhe** [comment]
The build tool used in this image is deprecated. Please move to [Cloud MTA Build Tool (MBT)](https://sap.github.io/cloud-mta-build-tool/) and [its docker image](https://hub.docker.com/r/devxci/mbtci) respectively.
